var flag = true;
var value = 12;
var person = "Mike";
var cards = [1, 2, 3];
var obj = { x: 0 };
obj = 15;
console.log("Value is equal to " + value);
console.log("Flag is equal to " + flag);
console.log("Person is equal to " + person);
console.log("Array values are equal to " + cards[0] + " " + cards[1] + " " + cards[2]);
console.log("Any value is " + obj);
obj = "hello";
console.log("Any value is " + obj);
